package com.example.exptrackpm.ui.screens.addexpense

import android.util.Log
import androidx.lifecycle.ViewModel
import com.example.exptrackpm.domain.model.Expense
import com.google.firebase.Timestamp
import com.google.firebase.auth.ktx.auth
import com.google.firebase.firestore.ktx.firestore
import com.google.firebase.ktx.Firebase
import kotlinx.coroutines.tasks.await

class AddExpenseViewModel : ViewModel(){

    private val db = Firebase.firestore

    fun addExpense(amount: Double, description: String, category: String, receiptUrl: String?) {
        val currentUser = Firebase.auth.currentUser
        if (currentUser == null) {
            Log.w("AddExpenseViewModel", "No user logged in.")
            return
        }
        val expense = Expense(
            id = "", // Firestore autogenerated id
            userId = currentUser.uid,
            amount = amount,
            description = description,
            category = category,
            date = Timestamp.now(),
            receiptUrl = receiptUrl
        )


        db.collection("expense")
            .add(expense)
            .addOnSuccessListener {
                Log.d("document", "Expense Successfully Created!")
            }
    }
}